{% set name = "openai-whisper" %}
{% set version = "20240930" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openai-whisper-{{ version }}.tar.gz
  sha256: b7178e9c1615576807a300024f4daa6353f7e1a815dac5e38c33f1ef055dd2d2

build:
  entry_points:
    - whisper=whisper.transcribe:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numba
    - numpy
    - pytorch  # [not linux64]
    - pytorch =*=cuda*  # [linux64]
    - tqdm
    - more-itertools
    - tiktoken
    - ffmpeg
    - triton >=2.0.0  # [linux64]

test:
  imports:
    - whisper
  commands:
    - whisper --help

about:
  home: https://github.com/openai/whisper
  summary: Robust Speech Recognition via Large-Scale Weak Supervision
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoxbro
